const express = require('express');
const controller = require('../controllers/customerController');
const { requireAdmin } = require('../middleware/auth');
const router = express.Router();
router.get('/', requireAdmin, controller.list);
router.get('/:id', requireAdmin, controller.getOne);
router.post('/', requireAdmin, controller.create);
router.put('/:id', requireAdmin, controller.update);
router.delete('/:id', requireAdmin, controller.remove);
module.exports = router;
