const products = [
  {
    "id": 1,
    "name": "Royal Kundan Necklace",
    "category": "Necklaces",
    "price": 2499,
    "originalPrice": 4999,
    "discount": 50,
    "rating": 4.8,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Elegant traditional necklace with intricate kundan work. Perfect for festive occasions and special events.",
    "image": "/products/regalia-1.jpg"
  },
  {
    "id": 2,
    "name": "Pearl Drop Earrings",
    "category": "Earrings",
    "price": 899,
    "originalPrice": 1799,
    "discount": 50,
    "rating": 4.6,
    "material": "Pearl & Alloy",
    "color": "White",
    "inStock": true,
    "description": "Delicate pearl drop earrings that add elegance to any look. Lightweight and comfortable.",
    "image": "/products/regalia-2.jpg"
  },
  {
    "id": 3,
    "name": "Gold Bangles Set",
    "category": "Bangles",
    "price": 1599,
    "originalPrice": 3199,
    "discount": 50,
    "rating": 4.7,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Set of 4 beautifully crafted gold bangles with traditional patterns. Perfect for celebrations.",
    "image": "/products/regalia-3.jpg"
  },
  {
    "id": 4,
    "name": "Emerald Stone Ring",
    "category": "Rings",
    "price": 799,
    "originalPrice": 1599,
    "discount": 50,
    "rating": 4.5,
    "material": "Premium Alloy",
    "color": "Green & Gold",
    "inStock": true,
    "description": "Stunning emerald stone ring with intricate detailing. A timeless piece for any occasion.",
    "image": "/products/regalia-4.jpg"
  },
  {
    "id": 5,
    "name": "Bridal Choker Necklace",
    "category": "Bridal Jewellery",
    "price": 3999,
    "originalPrice": 7999,
    "discount": 50,
    "rating": 4.9,
    "material": "Premium Alloy",
    "color": "Gold & Red",
    "inStock": true,
    "description": "Exquisite bridal choker with precious stone embellishments. The perfect piece for your special day.",
    "image": "/products/regalia-5.jpg"
  },
  {
    "id": 6,
    "name": "Chandelier Earrings",
    "category": "Earrings",
    "price": 1299,
    "originalPrice": 2599,
    "discount": 50,
    "rating": 4.7,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Gorgeous chandelier earrings that add glamour and sophistication to your appearance.",
    "image": "/products/regalia-6.jpg"
  },
  {
    "id": 7,
    "name": "Traditional Bangle Bracelet",
    "category": "Bracelets",
    "price": 699,
    "originalPrice": 1399,
    "discount": 50,
    "rating": 4.4,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Classic traditional bangle bracelet with timeless design. Versatile for daily wear or special events.",
    "image": "/products/regalia-7.jpg"
  },
  {
    "id": 8,
    "name": "Ruby Statement Ring",
    "category": "Rings",
    "price": 999,
    "originalPrice": 1999,
    "discount": 50,
    "rating": 4.6,
    "material": "Premium Alloy",
    "color": "Red & Gold",
    "inStock": true,
    "description": "Bold and beautiful ruby statement ring that makes a powerful impression.",
    "image": "/products/regalia-8.jpg"
  },
  {
    "id": 9,
    "name": "Gold Jhumka Earrings",
    "category": "Earrings",
    "price": 1199,
    "originalPrice": 2399,
    "discount": 50,
    "rating": 4.8,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Traditional jhumka earrings with bell-shaped design. Adds Indian elegance to any outfit.",
    "image": "/products/regalia-9.jpg"
  },
  {
    "id": 10,
    "name": "Sapphire Pendant Necklace",
    "category": "Necklaces",
    "price": 1899,
    "originalPrice": 3799,
    "discount": 50,
    "rating": 4.7,
    "material": "Premium Alloy",
    "color": "Blue & Gold",
    "inStock": true,
    "description": "Elegant sapphire pendant on a delicate chain. A sophisticated addition to any jewelry collection.",
    "image": "/products/regalia-10.jpg"
  },
  {
    "id": 11,
    "name": "Bridal Bangles Collection",
    "category": "Bridal Jewellery",
    "price": 4999,
    "originalPrice": 9999,
    "discount": 50,
    "rating": 5.0,
    "material": "Premium Alloy",
    "color": "Multi-Color",
    "inStock": true,
    "description": "Complete bridal bangle collection with intricate designs and precious stone work.",
    "image": "/products/regalia-11.jpg"
  },
  {
    "id": 12,
    "name": "Diamond-Look Studs",
    "category": "Earrings",
    "price": 499,
    "originalPrice": 999,
    "discount": 50,
    "rating": 4.5,
    "material": "Premium Alloy",
    "color": "Silver",
    "inStock": true,
    "description": "Elegant diamond-look stud earrings that sparkle beautifully. Perfect for everyday wear.",
    "image": "/products/regalia-1.jpg"
  },
  {
    "id": 13,
    "name": "Meenakari Necklace",
    "category": "Necklaces",
    "price": 1699,
    "originalPrice": 3399,
    "discount": 50,
    "rating": 4.8,
    "material": "Premium Alloy",
    "color": "Multi-Color",
    "inStock": true,
    "description": "Traditional meenakari work necklace with vibrant enamel designs.",
    "image": "/products/regalia-2.jpg"
  },
  {
    "id": 14,
    "name": "Temple Bangles Set",
    "category": "Bangles",
    "price": 1299,
    "originalPrice": 2599,
    "discount": 50,
    "rating": 4.6,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Set of temple-inspired bangles with traditional Hindu motifs.",
    "image": "/products/regalia-3.jpg"
  },
  {
    "id": 15,
    "name": "Cocktail Ring Set",
    "category": "Rings",
    "price": 1399,
    "originalPrice": 2799,
    "discount": 50,
    "rating": 4.5,
    "material": "Premium Alloy",
    "color": "Multi-Stone",
    "inStock": true,
    "description": "Set of three statement cocktail rings with colorful stone embellishments.",
    "image": "/products/regalia-4.jpg"
  },
  {
    "id": 16,
    "name": "Bridal Tiara",
    "category": "Bridal Jewellery",
    "price": 2999,
    "originalPrice": 5999,
    "discount": 50,
    "rating": 4.9,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Gorgeous bridal tiara that adds sparkle and elegance to your bridal look.",
    "image": "/products/regalia-5.jpg"
  },
  {
    "id": 17,
    "name": "Gold Chain Bracelet",
    "category": "Bracelets",
    "price": 999,
    "originalPrice": 1999,
    "discount": 50,
    "rating": 4.6,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Delicate gold chain bracelet that's perfect for layering or wearing alone.",
    "image": "/products/regalia-6.jpg"
  },
  {
    "id": 18,
    "name": "Nose Ring Collection",
    "category": "Earrings",
    "price": 399,
    "originalPrice": 799,
    "discount": 50,
    "rating": 4.4,
    "material": "Premium Alloy",
    "color": "Gold & Silver",
    "inStock": true,
    "description": "Collection of traditional nose rings in various designs and sizes.",
    "image": "/products/regalia-7.jpg"
  },
  {
    "id": 19,
    "name": "Statement Bangle Bracelet",
    "category": "Bracelets",
    "price": 1199,
    "originalPrice": 2399,
    "discount": 50,
    "rating": 4.7,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Bold statement bangle bracelet with modern artistic design.",
    "image": "/products/regalia-8.jpg"
  },
  {
    "id": 20,
    "name": "Bridal Armlet Set",
    "category": "Bridal Jewellery",
    "price": 2499,
    "originalPrice": 4999,
    "discount": 50,
    "rating": 4.8,
    "material": "Premium Alloy",
    "color": "Gold",
    "inStock": true,
    "description": "Traditional bridal armlet set with intricate stone work and traditional patterns.",
    "image": "/products/regalia-9.jpg"
  },
  {
    "id": 141,
    "name": "Emerald & Kundan Bridal Choker Set",
    "category": "Bridal Jewellery",
    "price": 2999,
    "originalPrice": 5999,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy, Kundan & Emerald Stones",
    "color": "Gold & Green",
    "inStock": true,
    "description": "A statement bridal choker with a cascade of kundan and emerald-toned drops, paired with a matching maang tikka. Perfect for weddings and festive occasions.",
    "image": "/products/fashion-jewels-1.jpg"
  },
  {
    "id": 142,
    "name": "Pearl Fringe Kundan Necklace Set",
    "category": "Necklaces",
    "price": 1499,
    "originalPrice": 2999,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy & Pearl",
    "color": "Gold & White",
    "inStock": true,
    "description": "A delicate gold-toned choker with dainty pearl drops and matching earrings - understated elegance for everyday festive wear.",
    "image": "/products/fashion-jewels-2.jpg"
  },
  {
    "id": 143,
    "name": "Ruby Pearl Cluster Choker Set",
    "category": "Necklaces",
    "price": 1699,
    "originalPrice": 3399,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy, Pearl & Enamel",
    "color": "Gold & Pink",
    "inStock": true,
    "description": "A pretty pink enamel choker set with clustered pearl drops and matching earrings, finished with a warm gold plating.",
    "image": "/products/fashion-jewels-3.jpg"
  },
  {
    "id": 144,
    "name": "Antique Ruby Jhumka Earrings",
    "category": "Earrings",
    "price": 999,
    "originalPrice": 1999,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy & Ruby Beads",
    "color": "Gold & Red",
    "inStock": true,
    "description": "Classic antique-finish jhumkas with a floral stud top and ruby bead drops - a versatile everyday festive pick.",
    "image": "/products/earrings-red-jhumka.jpg"
  },
  {
    "id": 145,
    "name": "Antique Emerald Jhumka Earrings",
    "category": "Earrings",
    "price": 999,
    "originalPrice": 1999,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy & Emerald Beads",
    "color": "Gold & Green",
    "inStock": true,
    "description": "Classic antique-finish jhumkas with a floral stud top and emerald bead drops - a versatile everyday festive pick.",
    "image": "/products/earrings-green-jhumka.jpg"
  },
  {
    "id": 146,
    "name": "Multicolor Stone Gold Kada",
    "category": "Bangles",
    "price": 1799,
    "originalPrice": 3599,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy & CZ Stones",
    "color": "Gold, Pink & Green",
    "inStock": true,
    "description": "A broad statement kada studded with rows of ruby, emerald and clear stones set in a gold-plated lattice.",
    "image": "/products/bangles-gemstone-kada.jpg"
  },
  {
    "id": 147,
    "name": "Gold Plated CZ Bangles (Set of 4)",
    "category": "Bangles",
    "price": 1599,
    "originalPrice": 3199,
    "discount": 50,
    "rating": 0,
    "material": "Gold Plated Alloy & CZ Stones",
    "color": "Gold",
    "inStock": true,
    "description": "A set of 4 slim gold-plated bangles lined with sparkling CZ stones - stackable and easy to dress up or down.",
    "image": "/products/bangles-set-of-4.jpg"
  },
  {
    "id": 148,
    "name": "Ivory Linen Cotton Kalamkari Saree",
    "category": "Sarees",
    "price": 600,
    "originalPrice": null,
    "discount": 0,
    "rating": 0,
    "material": "Linen Cotton",
    "color": "Ivory & Red",
    "inStock": true,
    "description": "These soft, lightweight Linen Cotton Sarees feature Digital Prints inspired by Kalamkari designs, including floral creepers, leafy vines, and peacocks, along with traditional decorated elephants on the pallu. Grab this trending collection! (Price + shipping)",
    "image": "/products/saree-cotton-elephant-print.jpg"
  },
  {
    "id": 149,
    "name": "Deep Purple Wine Velvet Saree",
    "category": "Sarees",
    "price": 699,
    "originalPrice": null,
    "discount": 0,
    "rating": 0,
    "material": "Velvet",
    "color": "Wine",
    "inStock": true,
    "description": "Drape yourself in supreme luxury with this breathtaking Deep Purple / Wine Velvet Saree. Crafted from ultra-soft, rich velvet fabric and beautifully enhanced with all-over delicate stonework/bootis, it features an exquisite, heavy scalloped border intricately detailed with shimmering embellishments.",
    "image": "/products/saree-wine-velvet.jpg"
  }
];

const { getPool } = require('../config/db');

async function seedProducts() {
  // The catalogue evolves over time.  Only seeding an empty table meant that
  // products added in a later release never appeared in an existing database.
  // INSERT IGNORE keeps any admin edits (and manually created products) intact
  // while adding only seed products whose ids are not already present.
  const sql = `INSERT IGNORE INTO products
    (id, name, category, price, original_price, discount, rating, material, color, in_stock, description, image)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`;

  let inserted = 0;
  for (const p of products) {
    const [result] = await getPool().query(sql, [
      p.id, p.name, p.category, p.price, p.originalPrice, p.discount, p.rating,
      p.material, p.color, p.inStock ? 1 : 0, p.description, p.image,
    ]);
    inserted += result.affectedRows;
  }
  return inserted > 0;
}

module.exports = { seedProducts };
